Zilla Plus for Amazon MSK Secure Public Access AWS CDK template
aklivity/zilla-plus-aws-templates pull request #38
Opened 2024-12-16 17:39 UTC by bmaidics

Fixes https://github.com/aklivity/zilla-plus-aws-templates/issues/1

2025-01-07 03:04 UTC, jfallows requested changes

2025-01-07 03:04 UTC, jfallows commented on amazon-msk/cdk/secure-public-access/cdk.json
> +    "publicTlsCertificateKey": "<your public tls certificate key ARN>",
Perhaps we can check to see if there is any standard naming convention to follow here?

2025-01-07 09:37 UTC, bmaidics commented on amazon-msk/cdk/secure-public-access/cdk.json
> +    "publicTlsCertificateKey": "<your public tls certificate key ARN>",
There is not really a standard convention that I could find. Some examples I found use camelCase some snake_case. Any preference for you?

2025-01-08 16:57 UTC, jfallows approved these changes

2025-01-08 16:58 UTC, merged